Convert inbox to TT
dreamwidth/dw-free pull request #2853
Opened 2020-12-10 00:23 UTC by momijizukamori

Mostly a straight convert of the BML with HTML/CSS for nicer responsive handling, but a few notes!
- This includes some tweaks to make the jquery autocomplete 1) look nicer inline and 2) be able to take a static array instead of just an endpoint to call back to
- the `no_proto_img` stuff is to make management buttons in the inbox cooperate with our newer JS without having to alter `LJ::img` which is a lot of places and thus likely to have weird knock-on effects
- I had some weird issues getting strings in `index.tt.text` to show up in `index.tt`? Worked around it by using existing strings from en.dat the two spots I needed them.

2020-12-10 23:58 UTC, kareila commented
Checks failed - does this need to be retidied?

2020-12-11 00:28 UTC, momijizukamori commented
Hmm, thought I ran tidy before I pushed. I'll double-check and see.

2021-02-15 19:16 UTC, zorkian requested changes
Some conversion comments that need to be addressed, one major one around form auth, and a few other places with similar comments. I started to nit on formatting but since most of this is copied from the BML, we don't need to address nits on formatting that code.

I didn't really spend a ton of time on the SCSS/JS/HTML, so that's something we'll want to either have other people dig into or just plan to push this when we're around to do fixes live.

2021-02-15 19:16 UTC, zorkian commented on views/inbox/compose.tt
> +    'stc/css/pages/inbox.css'
I'm vaguely surprised this list of files doesn't need trailing commas?

nit: using single quotes for some lines but double quotes for others kills the Mark

2021-02-15 19:16 UTC, zorkian commented on cgi-bin/DW/Controller/Inbox.pm
> +use strict;
This file is missing the header copyright notices and also the normal preamble (use v5.10 etc).

2021-02-15 19:16 UTC, zorkian commented on cgi-bin/DW/Controller/Inbox.pm
> +DW::Routing->register_rpc( "inbox_actions", \&action_handler, format => 'html' );
nit: If you aren't interpolating variables, use single-quotes for strings.

2021-02-15 19:16 UTC, zorkian commented on cgi-bin/DW/Controller/Inbox.pm
> +        or return error_ml( "$scope.error.couldnt_retrieve_inbox", { 'user' => $remote->{user} } );
nit: Quoting `'user'` here is unnecessary, and we prefer not to stylistically (reduces clutter). You only need to quote keys in hashes when the keys start with numbers or contain certain symbols.

2021-02-15 19:16 UTC, zorkian commented on cgi-bin/DW/Controller/Inbox.pm
> +        or return error_ml( "$scope.error.couldnt_retrieve_inbox", { 'user' => $remote->{user} } );
I just realized that a lot of this code came from the BML. You can ignore most of the nits... I don't need us to clean up the Perl we're copying from BML...

2021-02-15 19:16 UTC, zorkian commented on cgi-bin/DW/Controller/Inbox.pm
> +            BML::ehtml( \$contents );
Should this really call BML? Isn't there an equivalent LJ function?

2021-02-15 19:16 UTC, zorkian commented on cgi-bin/DW/Controller/Inbox.pm
> +    my $remote    = LJ::get_remote();
Can't this come out of `$rv` instead of calling out to `LJ::get_remote()`?

2021-02-15 19:16 UTC, zorkian commented on cgi-bin/DW/Controller/Inbox.pm
> +    my $form_auth = $args->{lj_form_auth};
This `$form_auth` seems to be unused so now I'm wondering if this needs to be checked in the `controller()` call above? I.e., if this handler is only invoked on POST, we probably need to validate the form auth?

2021-02-15 19:16 UTC, zorkian commented on cgi-bin/DW/Controller/Inbox.pm
> +            unless LJ::check_form_auth( $POST->{lj_form_auth} );
This is unnecessary since you passed `form_auth => 1` to the controller call.

2021-02-15 19:16 UTC, zorkian commented on cgi-bin/DW/Controller/Inbox.pm
> +            unless LJ::check_form_auth( $POST->{lj_form_auth} );
Unnecessary check.

2022-03-01 05:02 UTC, zorkian commented
Yikes how did I never circle back to this :< sorry.

2022-03-01 05:02 UTC, zorkian approved these changes

2022-03-01 20:26 UTC, merged